Space-traveller-Hub
agneta1991/space-traveller pull request #39
Opened 2023-08-31 12:24 UTC by agneta1991

## Project Pull Request: Space-Traveller-Hub Review

**Authors:** Agneta Pupienyte, Steven Ochieng

### Description
This pull request is for the review of our SpaceX App project. The project is built using React, Redux, and React Router, and it integrates with SpaceX APIs to fetch and display data about rockets and missions. The work was divided with Agneta working on rocket-related tasks and Steven handling mission-related tasks. The profile section was done collaboratively. We've also set up testing, adhered to best practices, and documented our work.

### Changes Made
- Created React App using Create React App.
- Integrated React Redux, Redux Logger, and React Router.
- Fetched and displayed data from SpaceX API endpoints for rockets and missions.
- Implemented rendering of rockets and missions.
- Developed functionality for reserving and canceling rockets and joining/leaving missions.
- Styled components using separate files for each.
- Set up testing using React Testing Library and Jest.

### Additional Notes
- The project adheres to best practices for HTML/CSS and JavaScript.
- The application design follows the specified requirements.
- All components and functions have been tested.
- We've avoided state mutations by updating the state immutably.

### Checklist
- [x] No linter errors.
- [x] Used correct Gitflow.
- [x] Documented work professionally.
- [x] Followed best practices for HTML, CSS, and JavaScript.
- [x] Fetched and displayed data from SpaceX APIs.
- [x] Implemented reservation and joining functionality using Redux.
- [x] Created conditional rendering for UI components.
- [x] Styled components according to design.
- [x] Implemented My Profile section.
- [x] Set up testing using React Testing Library and Jest.
- [x] Avoided state mutations.

2023-08-31 14:09 UTC, cynthiainga requested changes
Hi @agneta1991 & @Ochiengsteven, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights

- [ ] Follow Gitflow and GitHub flow ✔️ 
- [ ] Users can reserve rockets and cancel the reservation ✔️ 
- [ ] Users can join the mission and leave the mission ✔️ 
- [ ] Good commit history ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇🏾 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 14:09 UTC, cynthiainga commented on src/redux/rocketSlice.js
- [ ] As mentioned in the project requirements all Redux state slice files should be created in their own directory which means `rocketSlice` should be in the `rockets` directory 🙃 
- [ ] Please kindly do not disable linters errors, fixing linters helps us to write a clean and strong code base 😁

2023-08-31 14:09 UTC, cynthiainga commented on src/redux/missions/missionsSlice.js
> +  // eslint-disable-next-line no-useless-catch
- [ ] Please kindly do not disable linters, fixing linters helps us to write a strong and clean code base 😁

2023-08-31 14:09 UTC, cynthiainga commented on src/components/missions.js
> +// import './missionsTable.css';
- [ ] Please kindly do not disable linters, fixing linters helps us to write a strong and clean code base 😁 
- [ ] Kindly delete the commented line of code to keep your code clean 🙃

2023-08-31 14:09 UTC, cynthiainga commented on src/styles/Rockets.css
- [ ] Please kindly make sure to follow the given design 🙃 
  - Kindly make sure the `reserve` button has the same color as the button in the original design, also in the original design the button doesn’t have a border 😁 
  - Kindly make sure the `reservation status` has the same color as the one in the given design 🙃 

Your design

<img width="1011" alt="Screenshot 2023-08-31 at 16 53 50" src="https://github.com/agneta1991/space-traveller/assets/74501523/1ff127bd-c20e-497d-b042-6807a98ffa2c">

Given design

<img width="701" alt="Screenshot 2023-08-31 at 16 31 37" src="https://github.com/agneta1991/space-traveller/assets/74501523/fe44ce53-09eb-413d-b918-9591007ea7fd">

2023-08-31 14:09 UTC, cynthiainga commented on src/components/missions.css
- [ ] Good job so far, but you should make sure your design matches the given design "colors, padding, margin,..."

Your design

<img width="1011" alt="Screenshot 2023-08-31 at 16 54 05" src="https://github.com/agneta1991/space-traveller/assets/74501523/f335a378-6862-479b-a992-8f487924b8bf">

Given design

<img width="701" alt="Screenshot 2023-08-31 at 16 31 52" src="https://github.com/agneta1991/space-traveller/assets/74501523/e0d499d5-d39c-4a8b-9610-cb264923acd2">

2023-08-31 14:22 UTC, agneta1991 commented on src/styles/Rockets.css
@cynthiainga just a quick question regarding the css part, as in the requirements it does not say that our app has to match the design provided ( as there are no documentation on color codes, paddings, fonts etc. ) It just gives a suggestion that we can use bootstrap. Could you advise us how we can find the exact color codes and all? Thanks

2023-08-31 15:23 UTC, agneta1991 commented on src/styles/Rockets.css
@cynthiainga could you please respond as soon as you can as we would like to implement the changes, but as we don't know where to get the documentation for the css part, we are being held back. Thank you so much.

2023-08-31 15:36 UTC, cynthiainga commented on src/styles/Rockets.css
@agneta1991 I know it's not Figma and they didn’t give the exact color but you should use colors that are close to the given design. Hint `#1278f8 for reserve button`, and `#19a3b9 for reservation`, for padding is just an estimation but you should make sure that there is not much difference.

2023-08-31 19:30 UTC, Alusp requested changes
Hi @agneta1991 and @Ochiengsteven , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ![close](https://media.giphy.com/media/nJKDTpuxnZE7fb6Z1b/giphy.gif)

 ## Highlights
 Follow Gitflow and GitHub flow ✔️
 Users can reserve rockets and cancel the reservation ✔️
 Users can join the mission and leave the mission ✔️
 Good commit history ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alusp in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 19:30 UTC, Alusp commented on src/redux/rockets/rocketSlice.js
> +/* eslint-disable max-len */
- [ ] You have done really well in implementing the changes requested by the previous code reviewer, :clap: , However, as she mentioned, `"Please kindly do not disable linters, fixing linters helps us to write a strong and clean code base"` 😁, Please resolve that.

2023-08-31 19:30 UTC, Alusp commented on src/redux/rockets/rocketSlice.js
> +  // eslint-disable-next-line no-useless-catch
- [ ] You have done really well in implementing the changes requested by the previous code reviewer, :clap: , However, as she mentioned, `"Please kindly do not disable linters, fixing linters helps us to write a strong and clean code base"` 😁, Please resolve that.

2023-08-31 19:30 UTC, Alusp commented on src/components/MissionsProfile.css
- [ ] You have done really well in implementing the changes requested by the previous code reviewer, :clap: , However, as she mentioned, `"Please kindly do not disable linters, fixing linters helps us to write a strong and clean code base"` 😁, Please resolve that. `"you should make sure your design matches the given design "colors, padding, margin,..."`
matching your design to the given design requirements enhances the chances of creating a successful and well-rounded design solution that meets the needs of users, complies with regulations, and performs effectively and efficiently. :slightly_smiling_face: 

Below is an illustration of yours and the given Design, Please consider the red painting in  your  design :arrow_down: 

<table>
    <tr>
      <td>Your Design</td>
      <td>Given Design</td>
    </tr>
    <tr>
      <td>

![student D](https://github.com/agneta1991/space-traveller/assets/43528594/c03f2c3f-fcb1-4037-99df-3b3e64f401b5)


</td>
      <td>

<img width="1165" alt="space-travelers__missions" src="https://github.com/agneta1991/space-traveller/assets/43528594/abb90981-f097-4b16-8303-30f0eca7bb11">

</td>
    </tr>
  </table>

2023-09-01 06:25 UTC, Ibizugbe approved these changes
Hi @Team👋🏼👋🏼👋🏼, 

![approved](https://github.com/agneta1991/space-traveller/assets/64643995/4c165357-f481-4cbf-bef7-0e428f06f409)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Nice work making your project match the given design as requested by the previous reviewers👍🏼.
- [x] Linters are passing👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 06:50 UTC, merged